import { PageShell } from '@/components/PageShell';

const C = {
  fg: '#F1F0FF', sub: '#AEAECE', dim: '#A8A8C8', cyan: '#06B6D4',
  border: '#1A1A30',
  heading: "var(--font-cal-sans), 'Inter', sans-serif",
  body: "var(--font-inter), 'Helvetica Neue', sans-serif",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 48 }}>
      <h2 style={{ fontFamily: C.heading, fontSize: '1.6rem', fontWeight: 400, color: C.cyan, marginBottom: 16 }}>{title}</h2>
      <div style={{ fontFamily: C.body, fontSize: '0.88rem', fontWeight: 300, lineHeight: 1.9, color: C.sub }}>
        {children}
      </div>
    </div>
  );
}

export default function TermsPage() {
  return (
    <PageShell>
      <div style={{ maxWidth: 760, margin: '0 auto', padding: '80px 28px 120px' }}>
        <p style={{ fontFamily: C.body, fontSize: '0.7rem', letterSpacing: '0.22em', color: C.cyan, textTransform: 'uppercase', marginBottom: 16 }}>Legal</p>
        <h1 style={{ fontFamily: C.heading, fontWeight: 300, fontSize: 'clamp(2.4rem, 5vw, 3.6rem)', color: C.fg, marginBottom: 12, lineHeight: 1.1 }}>Terms of Service</h1>
        <p style={{ fontFamily: C.body, fontSize: '0.82rem', fontWeight: 300, color: C.dim, marginBottom: 56 }}>Last updated: April 2026</p>

        <Section title="Acceptance">
          <p>By downloading or using Symponia, you agree to these Terms of Service. If you do not agree, please do not use the app. These terms form a binding legal agreement between you and Boroto Ltd.</p>
        </Section>

        <Section title="The service">
          <p>Symponia provides an AI-powered reflective tool for personal exploration. This includes:</p>
          <ul style={{ marginTop: 10, paddingLeft: 20, lineHeight: 2 }}>
            <li>Three modes: Archetype, My Day, Conversation</li>
            <li>Animal archetype exploration and synthesis</li>
            <li>Daily personalised reflections</li>
            <li>Token-based access to conversations</li>
          </ul>
        </Section>

        <Section title="Not a medical service">
          <p>Symponia is <strong style={{ color: C.fg, fontWeight: 400 }}>not a medical, therapeutic, psychiatric, or psychological service</strong>. Nothing within the app or generated by Symponia constitutes professional advice, diagnosis, or treatment.</p>
          <p style={{ marginTop: 12 }}>If you are experiencing a mental health crisis, please contact a licensed professional or emergency services immediately. Symponia is a contemplative tool, not a substitute for professional care.</p>
        </Section>

        <div id="tokens"><Section title="Tokens and payments">
          <p>Symponia offers two purchase types:</p>
          <p style={{ marginTop: 16 }}><strong style={{ color: C.fg, fontWeight: 400 }}>Symponia Monthly subscription (£12.99/month):</strong> Includes 350 reflection sessions per month. A fresh allotment of 350 sessions arrives at each renewal; unused sessions do not carry over. Subscription renews automatically and can be cancelled at any time via your Apple ID settings. Access continues until the end of the current billing period.</p>
          <p style={{ marginTop: 16 }}><strong style={{ color: C.fg, fontWeight: 400 }}>Reflection Packs (top-up tokens):</strong> Reflection Pack 50 (£4.99, 50 sessions) and Reflection Pack 150 (£9.99, 150 sessions) are available for purchase while you have an active subscription. Top-up tokens never expire, even after cancellation.</p>
          <p style={{ marginTop: 16 }}><strong style={{ color: C.fg, fontWeight: 400 }}>New users</strong> receive a small free allowance to try Symponia before purchasing.</p>
          <p style={{ marginTop: 16 }}>Payment is processed securely by Apple via In-App Purchase. We never see or store your payment card details. All purchases are final; refunds are handled through Apple's standard refund process. Prices are displayed in the app and are subject to change.</p>
        </Section></div>

        <Section title="Acceptable use">
          <p>You agree not to:</p>
          <ul style={{ marginTop: 10, paddingLeft: 20, lineHeight: 2 }}>
            <li>Use Symponia for any unlawful purpose</li>
            <li>Attempt to reverse engineer, scrape, or copy Symponia's system</li>
            <li>Use the service to harass, abuse, or harm others</li>
            <li>Misrepresent your identity or age</li>
            <li>Use automated tools to interact with the service</li>
          </ul>
          <p style={{ marginTop: 12 }}>We reserve the right to suspend or terminate access for violations of these terms.</p>
        </Section>

        <Section title="Intellectual property">
          <p>All content within Symponia — including Symponia's AI system, animal archetype framework, interface design, and branding — is the intellectual property of Boroto Ltd. You may not reproduce, distribute, or create derivative works without our written permission.</p>
          <p style={{ marginTop: 12 }}>The content generated by Symponia in response to your input belongs to you. We do not claim ownership over your personal reflections or conversations.</p>
        </Section>

        <Section title="Availability">
          <p>We aim to keep Symponia available at all times but cannot guarantee uninterrupted access. The service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control. We are not liable for any loss resulting from service interruptions.</p>
        </Section>

        <Section title="Limitation of liability">
          <p>To the fullest extent permitted by law, Boroto Ltd shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the app. Our total liability to you for any claim arising from use of Symponia shall not exceed the amount you paid for tokens or subscriptions in the preceding 30 days.</p>
        </Section>

        <Section title="Changes to these terms">
          <p>We may update these Terms from time to time. We will notify you of material changes by updating the date above. Continued use of Symponia constitutes acceptance of the revised terms.</p>
        </Section>

        <Section title="Governing law">
          <p>These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
        </Section>

        <Section title="Contact">
          <p>For any questions about these Terms:</p>
          <p style={{ marginTop: 10 }}><a href="mailto:hello@symponia.io" style={{ color: C.cyan, textDecoration: 'none' }}>hello@symponia.io</a></p>
        </Section>
      </div>
    </PageShell>
  );
}
