import { PageShell } from '@/components/PageShell';

const C = {
  fg: '#eae6f8', sub: '#cac4e0', dim: '#a89ec8', cyan: '#5ce8d0',
  border: 'rgba(255,255,255,0.07)',
  heading: "var(--font-cormorant), 'Georgia', serif",
  body: "var(--font-inter), 'Helvetica Neue', sans-serif",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 48 }}>
      <h2 style={{ fontFamily: C.heading, fontSize: '1.6rem', fontWeight: 400, color: C.cyan, marginBottom: 16 }}>{title}</h2>
      <div style={{ fontFamily: C.body, fontSize: '0.88rem', fontWeight: 300, lineHeight: 1.9, color: C.sub }}>
        {children}
      </div>
    </div>
  );
}

export default function TermsPage() {
  return (
    <PageShell>
      <div style={{ maxWidth: 760, margin: '0 auto', padding: '80px 28px 120px' }}>
        <p style={{ fontFamily: C.body, fontSize: '0.7rem', letterSpacing: '0.22em', color: C.cyan, textTransform: 'uppercase', marginBottom: 16 }}>Legal</p>
        <h1 style={{ fontFamily: C.heading, fontWeight: 300, fontSize: 'clamp(2.4rem, 5vw, 3.6rem)', color: C.fg, marginBottom: 12, lineHeight: 1.1 }}>Terms of Service</h1>
        <p style={{ fontFamily: C.body, fontSize: '0.82rem', fontWeight: 300, color: C.dim, marginBottom: 56 }}>Last updated: April 2026</p>

        <Section title="Acceptance">
          <p>By downloading or using Symponia, you agree to these Terms of Service. If you do not agree, please do not use the app. These terms form a binding legal agreement between you and Symponia Ltd.</p>
        </Section>

        <Section title="The service">
          <p>Symponia provides an AI-powered reflective tool for personal exploration. This includes:</p>
          <ul style={{ marginTop: 10, paddingLeft: 20, lineHeight: 2 }}>
            <li>Oracle conversation modes (Sense, Animal, Daily, Dream, Shadow, Word)</li>
            <li>Animal archetype readings and synthesis</li>
            <li>Daily personalised reflections</li>
            <li>Token-based access to Oracle readings</li>
          </ul>
        </Section>

        <Section title="Not a medical service">
          <p>Symponia is <strong style={{ color: C.fg, fontWeight: 400 }}>not a medical, therapeutic, psychiatric, or psychological service</strong>. Nothing within the app or generated by the Oracle constitutes professional advice, diagnosis, or treatment.</p>
          <p style={{ marginTop: 12 }}>If you are experiencing a mental health crisis, please contact a licensed professional or emergency services immediately. Symponia is a contemplative tool, not a substitute for professional care.</p>
        </Section>

        <div id="tokens"><Section title="Tokens and payments">
          <p>Symponia uses a token system for Oracle readings. Each conversation exchange uses 1 token. New users receive 10 free readings. The following products are available for purchase within the app:</p>

          <div style={{ margin: '20px 0', padding: '20px 24px', borderRadius: 12, border: `0.5px solid rgba(255,255,255,0.1)`, background: 'rgba(255,255,255,0.02)' }}>
            <p style={{ color: C.fg, fontWeight: 400, marginBottom: 12 }}>Symponia Premium — Monthly Subscription</p>
            <ul style={{ paddingLeft: 20, lineHeight: 2 }}>
              <li>Price: £12.99 / month (auto-renewing)</li>
              <li>Includes: 350 oracle readings per month</li>
              <li>Tokens refresh every month at renewal. Unused tokens are replaced with a fresh 350.</li>
            </ul>
          </div>

          <div style={{ margin: '20px 0', padding: '20px 24px', borderRadius: 12, border: `0.5px solid rgba(255,255,255,0.1)`, background: 'rgba(255,255,255,0.02)' }}>
            <p style={{ color: C.fg, fontWeight: 400, marginBottom: 12 }}>Token Packs — One-time purchase</p>
            <ul style={{ paddingLeft: 20, lineHeight: 2 }}>
              <li>50 tokens — £4.99</li>
              <li>150 tokens — £9.99</li>
              <li>Tokens do not expire and carry over indefinitely.</li>
            </ul>
          </div>

          <p style={{ marginTop: 16 }}>The following applies to all purchases:</p>
          <ul style={{ marginTop: 10, paddingLeft: 20, lineHeight: 2 }}>
            <li>Payment will be charged to your Apple ID account at confirmation of purchase.</li>
            <li>Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current period.</li>
            <li>Manage or cancel your subscription in your Apple ID Settings at any time.</li>
            <li>Token pack purchases are non-refundable once tokens have been used.</li>
            <li>All purchases are final. Refunds are considered on a case-by-case basis — contact <a href="mailto:hello@symponia.io" style={{ color: C.cyan, textDecoration: 'none' }}>hello@symponia.io</a>.</li>
          </ul>
        </Section></div>

        <Section title="Acceptable use">
          <p>You agree not to:</p>
          <ul style={{ marginTop: 10, paddingLeft: 20, lineHeight: 2 }}>
            <li>Use Symponia for any unlawful purpose</li>
            <li>Attempt to reverse engineer, scrape, or copy the Oracle system</li>
            <li>Use the service to harass, abuse, or harm others</li>
            <li>Misrepresent your identity or age</li>
            <li>Use automated tools to interact with the service</li>
          </ul>
          <p style={{ marginTop: 12 }}>We reserve the right to suspend or terminate access for violations of these terms.</p>
        </Section>

        <Section title="Intellectual property">
          <p>All content within Symponia — including the Oracle system, animal archetype framework, interface design, and branding — is the intellectual property of Symponia Ltd. You may not reproduce, distribute, or create derivative works without our written permission.</p>
          <p style={{ marginTop: 12 }}>The content generated by the Oracle in response to your input belongs to you. We do not claim ownership over your personal reflections or conversations.</p>
        </Section>

        <Section title="Availability">
          <p>We aim to keep Symponia available at all times but cannot guarantee uninterrupted access. The service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control. We are not liable for any loss resulting from service interruptions.</p>
        </Section>

        <Section title="Limitation of liability">
          <p>To the fullest extent permitted by law, Symponia Ltd shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the app. Our total liability to you for any claim arising from use of Symponia shall not exceed the amount you paid for tokens or subscriptions in the preceding 30 days.</p>
        </Section>

        <Section title="Changes to these terms">
          <p>We may update these Terms from time to time. We will notify you of material changes by updating the date above. Continued use of Symponia constitutes acceptance of the revised terms.</p>
        </Section>

        <Section title="Governing law">
          <p>These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
        </Section>

        <Section title="Contact">
          <p>For any questions about these Terms:</p>
          <p style={{ marginTop: 10 }}><a href="mailto:hello@symponia.io" style={{ color: C.cyan, textDecoration: 'none' }}>hello@symponia.io</a></p>
        </Section>
      </div>
    </PageShell>
  );
}
